server:  port: 8081

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://startjpa.cm7ephy76u9y.ap-northeast-2.rds.amazonaws.com:3306/test_jpa?serverTimezone=UTC&characterEncoding=UTF-8    username: admin    password: 1q2w3e4r5t!      jpa :    properties :      hibernate :        format_sql:false    show-sql: false            hibernate :      dialect: org.hibernate.dialect.MySQL8Dialect      ddl-auto: update      naming:         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  output:    ansi:      enabled: NEVER      logging:  level:    root: info